
DESIGN = zxuno
DEVICE_NAME = xc6slx9
DEVICE_PACKAGE = tqg144
DEVICE_SPEED = 2
UCF_FILE = ../../src/syn-zxuno/zxuno_pins_vga2m.ucf

# Make all runs to place & route
all: bitstream

include ../makefile.inc
