
#RM = rm -rf
RM = del /q

SRCS = ../msx_pack.vhd \
	../cpu/t80_pack.vhd ../cpu/t80_alu.vhd ../cpu/t80_mcode.vhd ../cpu/t80_reg.vhd ../cpu/t80.vhd ../cpu/t80s.vhd \
	../video/vdp18/vdp18_pack-p.vhd ../video/vdp18/vdp18_addr_mux.vhd ../video/vdp18/vdp18_clk_gen.vhd \
	../video/vdp18/vdp18_palette.vhd ../video/vdp18/vdp18_col_mux.vhd ../video/vdp18/vdp18_cpuio.vhd \
	../video/vdp18/vdp18_ctrl.vhd ../video/vdp18/vdp18_hor_vert.vhd ../video/vdp18/vdp18_pattern.vhd \
	../video/vdp18/vdp18_sprite.vhd ../video/vdp18/dprame.vhd ../video/vdp18/dblscan.vhd \
	../video/vdp18/vdp18_core.vhd \
	../shared/fifo.vhd \
	../ram/spram.vhd ../ram/dpram.vhd \
	../peripheral/pio.vhd \
	../peripheral/ym2149s.vhd \
	../peripheral/exp_slot.vhd \
	../peripheral/memoryctl.vhd \
	../peripheral/romnextor.vhd \
	../peripheral/spi.vhd \
	../peripheral/swioports.vhd \
	../peripheral/escci/scc_wave.vhd \
	../peripheral/escci/escci.vhd \
	../peripheral/vm2413/vm2413-pack.vhd ../peripheral/vm2413/attacktable.vhd \
	../peripheral/vm2413/attacktablemul.vhd ../peripheral/vm2413/envelopememory.vhd \
	../peripheral/vm2413/envelopegenerator.vhd ../peripheral/vm2413/feedbackmemory.vhd \
	../peripheral/vm2413/interpolatemul.vhd ../peripheral/vm2413/lineartablemul.vhd \
	../peripheral/vm2413/lineartable.vhd ../peripheral/vm2413/outputmemory.vhd \
	../peripheral/vm2413/outputgenerator.vhd ../peripheral/vm2413/phasememory.vhd \
	../peripheral/vm2413/phasegenerator.vhd ../peripheral/vm2413/registermemory.vhd \
	../peripheral/vm2413/sinetable.vhd ../peripheral/vm2413/slotcounter.vhd \
	../peripheral/vm2413/summixer.vhd ../peripheral/vm2413/temporalmixer.vhd \
	../peripheral/vm2413/voicerom.vhd ../peripheral/vm2413/voicememory.vhd \
	../peripheral/vm2413/operator.vhd ../peripheral/vm2413/controller.vhd \
	../peripheral/vm2413/opll.vhd \
	ipl_rom.vhd \
	../clocks.vhd ../msx.vhd \

include ../make.inc
