
#RM = rm -rf
RM = del /q

SRCS = ..\vdp18_pack-p.vhd ..\vdp18_addr_mux.vhd ..\vdp18_clk_gen.vhd \
	..\vdp18_palette.vhd ..\vdp18_col_mux.vhd ..\vdp18_cpuio.vhd \
	..\vdp18_ctrl.vhd ..\vdp18_hor_vert.vhd ..\vdp18_pattern.vhd \
	..\vdp18_sprite.vhd ..\dprame.vhd ..\dblscan.vhd ..\vdp18_core.vhd

include ../../../make.inc
