
#RM = rm -rf
RM = del /q

SRCS = ../vm2413-pack.vhd ../attacktable.vhd ../attacktablemul.vhd \
	../envelopememory.vhd ../envelopegenerator.vhd ../feedbackmemory.vhd \
	../interpolatemul.vhd ../lineartablemul.vhd ../lineartable.vhd \
	../outputmemory.vhd ../outputgenerator.vhd ../phasememory.vhd \
	../phasegenerator.vhd ../registermemory.vhd ../sinetable.vhd \
	../slotcounter.vhd ../summixer.vhd ../temporalmixer.vhd \
	../voicerom.vhd ../voicememory.vhd ../operator.vhd \
	../controller.vhd ../opll.vhd

include ../../../make.inc
