
DESIGN = wxedax
DEVICE_NAME = xc6slx9
DEVICE_PACKAGE = tqg144
DEVICE_SPEED = 2
UCF_FILE = ../../src/syn-wxedax/wxedax_pins.ucf

# Make all runs to place & route
all: bitstream

include ../makefile.inc
