
all: qmxc6slx16 wxedax zxuno zxuno_vga2m

DE1:
	make -C %@

DE2:
	make -C %@

multicore:
	make -C %@

multicore2:
	make -C %@

qmxc6slx16:
	make -C %@

wxeda:
	make -C %@

wxedax:
	make -C %@

zxuno:
	make -C %@

zxuno_vga2m:
	make -C %@
